FrontToBackEnd/ViewComponents/FooterViewComponent.cs
using FrontToBackEnd.Models;
using FrontToBackEnd.Service;
using FrontToBackEnd.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontToBackEnd.ViewComponents
{
    public class FooterViewComponent: ViewComponent
    {
        private readonly LayoutService _layoutService;
        public FooterViewComponent(LayoutService layoutService)
        {
            _layoutService = layoutService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> categories = _layoutService.GetCategories();
            List<CategoryName> categoryNames = _layoutService.GetCategoryNames();
            List<Fruit> fruits = _layoutService.GetFruit();
            List<Beverage> beverages = _layoutService.GetBeverage();
            LayoutVM layoutVM = new LayoutVM
            {
                Categories = categories,
                CategoryNames = categoryNames,
                Fruits = fruits,
                Beverages = beverages
            };
            return (await Task.FromResult(View(layoutVM)));
        }
    }
}

FrontToBackEnd/ViewComponents/HeaderViewComponent.cs
using FrontToBackEnd.Data;
using FrontToBackEnd.Models;
using FrontToBackEnd.Service;
using FrontToBackEnd.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontToBackEnd.ViewComponents
{
    public class HeaderViewComponent: ViewComponent
    {
        private readonly LayoutService _layoutService;
        public HeaderViewComponent(LayoutService layoutService)
        {
            _layoutService = layoutService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> categories =  _layoutService.GetCategories();
            List<CategoryName> categoryNames =  _layoutService.GetCategoryNames();
            List<Fruit> fruits =  _layoutService.GetFruit();
            List<Beverage> beverages =  _layoutService.GetBeverage();
            LayoutVM layoutVM = new LayoutVM
            {
                Categories =categories,
                CategoryNames= categoryNames,
                Fruits = fruits,
                Beverages= beverages
            };
            int cardCount = 0;
            decimal totalPrice=0;
            if (Request.Cookies["basket"] != null)
            {
                List<BasketVM> basket = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["basket"]);
                cardCount = basket.Sum(m => m.Count);
                List<BasketDetailVM> basketDetail = JsonConvert.DeserializeObject<List<BasketDetailVM>>(Request.Cookies["basket"]);
                totalPrice = basketDetail.Sum(m => m.NewPrice);
            }
            else
            {
                cardCount = 0;
                totalPrice = 0;
            }

            ViewBag.count = cardCount;
            ViewBag.totalPrice = totalPrice;
            return (await Task.FromResult(View(layoutVM)));
        }
    }
}

FrontToBackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="Shortcut Icon" href="https://klbtheme.com/bacola/wp-content/uploads/2021/08/favicon.png"
          type="image/x-icon">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.1.9/sweetalert2.min.css"
          integrity="sha512-cyIcYOviYhF0bHIhzXWJQ/7xnaBuIIOecYoPZBgJHQKFPo+TOBA+BY1EnTpmM8yKDU4ZdI3UGccNGCEUdfbBqw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/5e5d9e530b.js" crossorigin="anonymous"></script>
    @RenderSection("style", false)
    @*<link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
        <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="~/assets/css/flipclock.css">






    *@


</head>

<body>

    @await Component.InvokeAsync("Header")

    @RenderBody()

    @await Component.InvokeAsync("Footer")




    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/flipclock.min.js"></script>
    <script src="~/assets/js/script.js"></script>
</body>

</html>